name: Test Build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2-beta
      - run: 'echo "${{ secrets.CLI_CONFIG }}" > src/config.ts'
      - run: yarn install
      - run: yarn build
